export const data = [
  // Champions League
  { x: "Real Madrid", y: "2000", value: 2, country: "Spain", competition: "UCL" },
  { x: "Valencia", y: "2000", value: 1, country: "Spain", competition: "UCL" },
  { x: "Bayern Munich", y: "2001", value: 2, country: "Germany", competition: "UCL" },
  { x: "Valencia", y: "2001", value: 1, country: "Spain", competition: "UCL" },
  { x: "Real Madrid", y: "2002", value: 2, country: "Spain", competition: "UCL" },
  { x: "Bayer Leverkusen", y: "2002", value: 1, country: "Germany", competition: "UCL" },
  { x: "Milan", y: "2003", value: 2, country: "Italy", competition: "UCL" },
  { x: "Juventus", y: "2003", value: 1, country: "Italy", competition: "UCL" },
  { x: "Porto", y: "2004", value: 2, country: "Portugal", competition: "UCL" },
  { x: "Monaco", y: "2004", value: 1, country: "France", competition: "UCL" },
  { x: "Liverpool", y: "2005", value: 2, country: "England", competition: "UCL" },
  { x: "Milan", y: "2005", value: 1, country: "Italy", competition: "UCL" },
  { x: "Barcelona", y: "2006", value: 2, country: "Spain", competition: "UCL" },
  { x: "Arsenal", y: "2006", value: 1, country: "England", competition: "UCL" },
  { x: "Milan", y: "2007", value: 2, country: "Italy", competition: "UCL" },
  { x: "Liverpool", y: "2007", value: 1, country: "England", competition: "UCL" },
  { x: "Manchester United", y: "2008", value: 2, country: "England", competition: "UCL" },
  { x: "Chelsea", y: "2008", value: 1, country: "England", competition: "UCL" },
  { x: "Barcelona", y: "2009", value: 2, country: "Spain", competition: "UCL" },
  { x: "Manchester United", y: "2009", value: 1, country: "England", competition: "UCL" },
  { x: "Inter Milan", y: "2010", value: 2, country: "Italy", competition: "UCL" },
  { x: "Bayern Munich", y: "2010", value: 1, country: "Germany", competition: "UCL" },
  { x: "Barcelona", y: "2011", value: 2, country: "Spain", competition: "UCL" },
  { x: "Manchester United", y: "2011", value: 1, country: "England", competition: "UCL" },
  { x: "Chelsea", y: "2012", value: 2, country: "England", competition: "UCL" },
  { x: "Bayern Munich", y: "2012", value: 1, country: "Germany", competition: "UCL" },
  { x: "Bayern Munich", y: "2013", value: 2, country: "Germany", competition: "UCL" },
  { x: "Borussia Dortmund", y: "2013", value: 1, country: "Germany", competition: "UCL" },
  { x: "Real Madrid", y: "2014", value: 2, country: "Spain", competition: "UCL" },
  { x: "Atlético Madrid", y: "2014", value: 1, country: "Spain", competition: "UCL" },
  { x: "Barcelona", y: "2015", value: 2, country: "Spain", competition: "UCL" },
  { x: "Juventus", y: "2015", value: 1, country: "Italy", competition: "UCL" },
  { x: "Real Madrid", y: "2016", value: 2, country: "Spain", competition: "UCL" },
  { x: "Atlético Madrid", y: "2016", value: 1, country: "Spain", competition: "UCL" },
  { x: "Real Madrid", y: "2017", value: 2, country: "Spain", competition: "UCL" },
  { x: "Juventus", y: "2017", value: 1, country: "Italy", competition: "UCL" },
  { x: "Real Madrid", y: "2018", value: 2, country: "Spain", competition: "UCL" },
  { x: "Liverpool", y: "2018", value: 1, country: "England", competition: "UCL" },
  { x: "Liverpool", y: "2019", value: 2, country: "England", competition: "UCL" },
  { x: "Tottenham Hotspur", y: "2019", value: 1, country: "England", competition: "UCL" },
  { x: "Bayern Munich", y: "2020", value: 2, country: "Germany", competition: "UCL" },
  { x: "Paris Saint-Germain", y: "2020", value: 1, country: "France", competition: "UCL" },
  { x: "Chelsea", y: "2021", value: 2, country: "England", competition: "UCL" },
  { x: "Manchester City", y: "2021", value: 1, country: "England", competition: "UCL" },
  { x: "Real Madrid", y: "2022", value: 2, country: "Spain", competition: "UCL" },
  { x: "Liverpool", y: "2022", value: 1, country: "England", competition: "UCL" },
  { x: "Manchester City", y: "2023", value: 2, country: "England", competition: "UCL" },
  { x: "Inter Milan", y: "2023", value: 1, country: "Italy", competition: "UCL" },
  { x: "Real Madrid", y: "2024", value: 2, country: "Spain", competition: "UCL" },
  { x: "Borussia Dortmund", y: "2024", value: 1, country: "Germany", competition: "UCL" },

  // Europa League
  { x: "Galatasaray", y: "2000", value: 2, country: "Turkey", competition: "UEL" },
  { x: "Arsenal", y: "2000", value: 1, country: "England", competition: "UEL" },
  { x: "Liverpool", y: "2001", value: 2, country: "England", competition: "UEL" },
  { x: "Deportivo Alavés", y: "2001", value: 1, country: "Spain", competition: "UEL" },
  { x: "Feyenoord", y: "2002", value: 2, country: "Netherlands", competition: "UEL" },
  { x: "Borussia Dortmund", y: "2002", value: 1, country: "Germany", competition: "UEL" },
  { x: "Porto", y: "2003", value: 2, country: "Portugal", competition: "UEL" },
  { x: "Celtic", y: "2003", value: 1, country: "Scotland", competition: "UEL" },
  { x: "Valencia", y: "2004", value: 2, country: "Spain", competition: "UEL" },
  { x: "Marseille", y: "2004", value: 1, country: "France", competition: "UEL" },
  { x: "CSKA Moscow", y: "2005", value: 2, country: "Russia", competition: "UEL" },
  { x: "Sporting CP", y: "2005", value: 1, country: "Portugal", competition: "UEL" },
  { x: "Sevilla", y: "2006", value: 2, country: "Spain", competition: "UEL" },
  { x: "Middlesbrough", y: "2006", value: 1, country: "England", competition: "UEL" },
  { x: "Sevilla", y: "2007", value: 2, country: "Spain", competition: "UEL" },
  { x: "Espanyol", y: "2007", value: 1, country: "Spain", competition: "UEL" },
  { x: "Zenit", y: "2008", value: 2, country: "Russia", competition: "UEL" },
  { x: "Rangers", y: "2008", value: 1, country: "Scotland", competition: "UEL" },
  { x: "Shakhtar Donetsk", y: "2009", value: 2, country: "Ukraine", competition: "UEL" },
  { x: "Werder Bremen", y: "2009", value: 1, country: "Germany", competition: "UEL" },
  { x: "Atlético Madrid", y: "2010", value: 2, country: "Spain", competition: "UEL" },
  { x: "Fulham", y: "2010", value: 1, country: "England", competition: "UEL" },
  { x: "Porto", y: "2011", value: 2, country: "Portugal", competition: "UEL" },
  { x: "Braga", y: "2011", value: 1, country: "Portugal", competition: "UEL" },
  { x: "Atlético Madrid", y: "2012", value: 2, country: "Spain", competition: "UEL" },
  { x: "Athletic Bilbao", y: "2012", value: 1, country: "Spain", competition: "UEL" },
  { x: "Chelsea", y: "2013", value: 2, country: "England", competition: "UEL" },
  { x: "Benfica", y: "2013", value: 1, country: "Portugal", competition: "UEL" },
  { x: "Sevilla", y: "2014", value: 2, country: "Spain", competition: "UEL" },
  { x: "Benfica", y: "2014", value: 1, country: "Portugal", competition: "UEL" },
  { x: "Sevilla", y: "2015", value: 2, country: "Spain", competition: "UEL" },
  { x: "Dnipro", y: "2015", value: 1, country: "Ukraine", competition: "UEL" },
  { x: "Sevilla", y: "2016", value: 2, country: "Spain", competition: "UEL" },
  { x: "Liverpool", y: "2016", value: 1, country: "England", competition: "UEL" },
  { x: "Manchester United", y: "2017", value: 2, country: "England", competition: "UEL" },
  { x: "Ajax", y: "2017", value: 1, country: "Netherlands", competition: "UEL" },
  { x: "Atlético Madrid", y: "2018", value: 2, country: "Spain", competition: "UEL" },
  { x: "Marseille", y: "2018", value: 1, country: "France", competition: "UEL" },
  { x: "Chelsea", y: "2019", value: 2, country: "England", competition: "UEL" },
  { x: "Arsenal", y: "2019", value: 1, country: "England", competition: "UEL" },
  { x: "Sevilla", y: "2020", value: 2, country: "Spain", competition: "UEL" },
  { x: "Inter Milan", y: "2020", value: 1, country: "Italy", competition: "UEL" },
  { x: "Villarreal", y: "2021", value: 2, country: "Spain", competition: "UEL" },
  { x: "Manchester United", y: "2021", value: 1, country: "England", competition: "UEL" },
  { x: "Eintracht Frankfurt", y: "2022", value: 2, country: "Germany", competition: "UEL" },
  { x: "Rangers", y: "2022", value: 1, country: "Scotland", competition: "UEL" },
  { x: "Sevilla", y: "2023", value: 2, country: "Spain", competition: "UEL" },
  { x: "Roma", y: "2023", value: 1, country: "Italy", competition: "UEL" },
  { x: "Atalanta", y: "2024", value: 2, country: "Italy", competition: "UEL" },
  { x: "Bayer Leverkusen", y: "2024", value: 1, country: "Germany", competition: "UEL" }
];

export const mapping = {
  columns: { value: "x" },  // Team name
  rows: { value: "y" },     // Year
  color: { value: "value" } // 1 = runner-up, 2 = champion
};

export const visualOptions = {};

